# Generated by Django 4.2.21 on 2025-06-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_phone_dealerimage_dealeradress_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
