# Generated by Django 4.2.21 on 2025-06-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_address_delete_dealeradress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealerImage',
        ),
    ]
