services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ggcar
      POSTGRES_USER: ggcaruser
      POSTGRES_PASSWORD: ggcarpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn gg_car.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: ggcar
      POSTGRES_USER: ggcaruser
      POSTGRES_PASSWORD: ggcarpass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_ENV: development

volumes:
  pgdata:
