# Generated by Django 4.2.21 on 2025-06-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_year_generation_car_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='generation',
        ),
        migrations.AddField(
            model_name='model',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Generation',
        ),
    ]
