# Generated by Django 4.2.21 on 2025-06-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_color_alter_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN'),
        ),
    ]
