# Generated by Django 4.2.21 on 2025-06-01 21:07

import cars.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cars.utils.brand_image_upload_path),
        ),
        migrations.AddField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cars.utils.model_image_upload_path),
        ),
    ]
